# Generated by Django 4.2.30 on 2026-04-27 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DECLARANT', 'Déclarant'), ('RISQUES_OP', 'Responsable Risques opérationnels'), ('DIR_RISQUES', 'Directeur Gestion des Risques'), ('ADMIN', 'Administrateur')], default='DECLARANT', max_length=30)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
