# Generated by Django 4.2.30 on 2026-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('V0', 'V0'), ('V1', 'V1')], default='', max_length=10)),
                ('date_declaration', models.DateField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateField(blank=True, null=True)),
                ('agence', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('direction', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('Direction Risques', 'Direction Risques'), ('Direction Audit et Inspection des services', 'Direction Audit et Inspection des services'), ('Service de  Conformité', 'Service de  Conformité'), ('Direction  Commerciale', 'Direction  Commerciale'), ('Direction des engagements', 'Direction des engagements'), ('Direction Financement du secteur agricole', 'Direction Financement du secteur agricole'), ('Département Juridique, Recouvrement et Contentieux', 'Département Juridique, Recouvrement et Contentieux'), ('Département des Opérations', 'Département des Opérations'), ('Direction Ressources Humaines et materiels', 'Direction Ressources Humaines et materiels'), ('Direction de la Comptabilité et Finance', 'Direction de la Comptabilité et Finance'), ("Direction du système d'information", "Direction du système d'information"), ('Direction banque digitale et stratégies', 'Direction banque digitale et stratégies')], default='', max_length=200)),
                ('nom_prenom_declarant', models.CharField(blank=True, default='', max_length=200)),
                ('fonction', models.CharField(blank=True, default='', max_length=200)),
                ('poste_telephonique', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_debut_incident', models.DateField(blank=True, null=True)),
                ('date_decouverte_incident', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('incident_lie_risque_credit', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('OUI', 'OUI'), ('NON', 'NON')], default='', max_length=3)),
                ('categorisation_baloise', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('1-       Fraude interne', '1-       Fraude interne'), ('2-       Fraude externe', '2-       Fraude externe'), ('3-       Pratiques sociales et sécurité sur le lieu de travail', '3-       Pratiques sociales et sécurité sur le lieu de travail'), ('4-       Clients Produits et Pratiques commerciales', '4-       Clients Produits et Pratiques commerciales'), ('5-       Dommages aux actifs matériels', '5-       Dommages aux actifs matériels'), ("6-       Interruption d'activité et défaillance de systèmes", "6-       Interruption d'activité et défaillance de systèmes"), ('7-       Exécution, Livraison et Gestion des Processus', '7-       Exécution, Livraison et Gestion des Processus')], default='', max_length=255)),
                ('sous_categorie_incident', models.CharField(blank=True, default='', max_length=255)),
                ('macro_processus', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ("1-Gérer  l'Audit et l'Inspection des services", "1-Gérer  l'Audit et l'Inspection des services"), ('2-Gérer la Conformité', '2-Gérer la Conformité'), ('3-Gérer le contrôle permanent', '3-Gérer le contrôle permanent'), ('4-Gérer la qualité', '4-Gérer la qualité'), ("5-Gérer l'administration de la Direction générale", "5-Gérer l'administration de la Direction générale"), ('6-Gérer le Commercial', '6-Gérer le Commercial'), ('7-Gérer les Engagements', '7-Gérer les Engagements'), ('8-Gérer la banque digitale et la stratégie', '8-Gérer la banque digitale et la stratégie'), ('9-Gérer le Juridique et le Recouvrement', '9-Gérer le Juridique et le Recouvrement'), ('10-Gérer les Opérations', '10-Gérer les Opérations'), ("11-Gérer l'Administration & RH, materiel", "11-Gérer l'Administration & RH, materiel"), ('12-Gérer la Comptabilité et la Finance', '12-Gérer la Comptabilité et la Finance'), ("13-Gérer le système d'information", "13-Gérer le système d'information"), ('14-Gérer le financement du secteur agricole', '14-Gérer le financement du secteur agricole'), ('15-Gérer le risque', '15-Gérer le risque')], default='', max_length=255)),
                ('processus', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ("1-1-Gérer  l'Audit interne", "1-1-Gérer  l'Audit interne"), ("1-2-Gérer l'Audit informatique", "1-2-Gérer l'Audit informatique"), ('2-1-Gérer la conformité', '2-1-Gérer la conformité'), ('3-1-Gérer le contrôle permanent', '3-1-Gérer le contrôle permanent'), ('4-1-Gérer la qualité', '4-1-Gérer la qualité'), ("5-1-Gérer l'administration de la Direction générale", "5-1-Gérer l'administration de la Direction générale"), ('6-1-Gérer la clientèle institutionnelle', '6-1-Gérer la clientèle institutionnelle'), ('6-2-Gérer clientèle Réseau Agence', '6-2-Gérer clientèle Réseau Agence'), ('6-3-Gérer les PME/PMI', '6-3-Gérer les PME/PMI'), ('6-4-Gérer les Agences /Bureaux', '6-4-Gérer les Agences /Bureaux'), ("7-1-Gérer l'analyse des crédits", "7-1-Gérer l'analyse des crédits"), ("7-2-Gérer l'administration de crédits", "7-2-Gérer l'administration de crédits"), ('7-3-Gérer les engagements par signature', '7-3-Gérer les engagements par signature'), ('8-1-Gérer le marketing et la stratégie', '8-1-Gérer le marketing et la stratégie'), ('8-2-Gérer le digital / moyen de paiements', '8-2-Gérer le digital / moyen de paiements'), ('9-1-Gérer le Juridique', '9-1-Gérer le Juridique'), ('9-2-Gérer le Recouvrement', '9-2-Gérer le Recouvrement'), ('10-1-Gérer les Opérations Locales', '10-1-Gérer les Opérations Locales'), ("10-2-Gérer les Opérations avec l'Etranger", "10-2-Gérer les Opérations avec l'Etranger"), ('10-3-Gérer les transferts Rapides', '10-3-Gérer les transferts Rapides'), ('11-1-Gérer le personnel et la formation', '11-1-Gérer le personnel et la formation'), ('11-2-Gérer le Materiel et la Sécurité', '11-2-Gérer le Materiel et la Sécurité'), ('12-1-Gérer la comptabilité et le reporting', '12-1-Gérer la comptabilité et le reporting'), ('12-2-Gérer le contrôle de gestion', '12-2-Gérer le contrôle de gestion'), ('12-3-Gérer la Trésorerie', '12-3-Gérer la Trésorerie'), ("13-1-Gérer l'exploitation et la production", "13-1-Gérer l'exploitation et la production"), ("13-2-Gérer l'Administration Réseaux, Télécom et Sécurité", "13-2-Gérer l'Administration Réseaux, Télécom et Sécurité"), ('13-3-Gérer la maintenance et le développement', '13-3-Gérer la maintenance et le développement'), ('14-1-Gérer le Partenariat', '14-1-Gérer le Partenariat'), ("14-2-Gérer l'Etude et l'analyse crédit agricole", "14-2-Gérer l'Etude et l'analyse crédit agricole"), ('14-3-Gérer le suivi crédit agricole', '14-3-Gérer le suivi crédit agricole'), ("14-4-Gérer l'Unité de gestion des projets", "14-4-Gérer l'Unité de gestion des projets"), ('15-1-Gérer le risque opérationnel et stratégique', '15-1-Gérer le risque opérationnel et stratégique'), ('15-2-Gérer le risque de crédit', '15-2-Gérer le risque de crédit')], default='', max_length=255)),
                ('domaine_activite', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('Risques', 'Risques'), ('Audit', 'Audit'), ('Conformité et Contrôle Permanent', 'Conformité et Contrôle Permanent'), ('Développement des Affaires', 'Développement des Affaires'), ('Opérations bancaires', 'Opérations bancaires')], default='', max_length=255)),
                ('incident_si', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('OUI', 'OUI'), ('NON', 'NON')], default='', max_length=3)),
                ('incident_non_conformite', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('OUI', 'OUI'), ('NON', 'NON')], default='', max_length=3)),
                ('montant_estime_perte', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('comptabilisation_perte', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('OUI', 'OUI'), ('NON', 'NON')], default='', max_length=3)),
                ('date_comptabilisation_perte', models.DateField(blank=True, null=True)),
                ('montant_recuperations', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('date_recuperation', models.DateField(blank=True, null=True)),
                ('nature_recuperation', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('Assurance', 'Assurance'), ('Remboursement', 'Remboursement'), ('Autre (à préciser)', 'Autre (à préciser)')], default='', max_length=255)),
                ('montant_net_perte', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('criticite', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Fort', 'Fort'), ('Majeur', 'Majeur')], default='', max_length=50)),
                ('impact_pca', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('OUI', 'OUI'), ('NON', 'NON')], default='', max_length=3)),
                ('statut_incident', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('Clos', 'Clos'), ('En cours de résolution', 'En cours de résolution'), ('Non résolu', 'Non résolu')], default='', max_length=50)),
                ('date_butoire_resolution', models.DateField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
