# Generated by Django 4.2.30 on 2026-04-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesureImmediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('mesure', models.CharField(blank=True, default='', max_length=500)),
                ('responsable_mise_en_place', models.CharField(blank=True, default='', max_length=200)),
                ('direction_service_responsable', models.CharField(blank=True, default='', max_length=200)),
                ('date_mise_en_place', models.DateField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_immediates', to='incidents.incident')),
            ],
            options={
                'ordering': ['numero', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActionCorrective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('action', models.CharField(blank=True, default='', max_length=500)),
                ('responsable_mise_en_place', models.CharField(blank=True, default='', max_length=200)),
                ('direction_service_responsable', models.CharField(blank=True, default='', max_length=200)),
                ('statut_action', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('Clos', 'Clos'), ('En cours de résolution', 'En cours de résolution'), ('Non résolu', 'Non résolu')], default='', max_length=50)),
                ('delai_mise_en_place', models.DateField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_correctives', to='incidents.incident')),
            ],
            options={
                'ordering': ['numero', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvisValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RISQUES_OP', 'Responsable Risques opérationnels'), ('DIR_GESTION_RISQUES', 'Directeur de la gestion des Risques')], max_length=40)),
                ('ok_ko', models.CharField(blank=True, choices=[('', 'Sélectionner…'), ('OK', 'OK'), ('KO', 'KO')], default='', max_length=2)),
                ('date', models.DateField(blank=True, null=True)),
                ('opinion', models.TextField(blank=True, default='')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_validations', to='incidents.incident')),
            ],
            options={
                'ordering': ['role', 'id'],
                'unique_together': {('incident', 'role')},
            },
        ),
    ]
